"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000";
export default function RegisterPage() { const router = useRouter(); const [form, setForm] = useState({ full_name: "", email: "", password: "", confirm: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const update = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setError(""); if (form.password.length < 8 || !/[A-Z]/.test(form.password) || !/[a-z]/.test(form.password) || !/\d/.test(form.password)) { setError("Use at least 8 characters with uppercase, lowercase, and a number."); return; } if (form.password !== form.confirm) { setError("Passwords do not match."); return; } setLoading(true); try { const response = await fetch(`${API_BASE}/api/v1/auth/register`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ full_name: form.full_name, email: form.email, password: form.password }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? "We couldn't create your account."); const login = await fetch(`${API_BASE}/api/v1/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: form.email, password: form.password }) }); const token = await login.json(); localStorage.setItem("void_access_token", token.access_token); router.replace("/onboarding"); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Registration failed."); } finally { setLoading(false); } }
  return <main className="auth-page"><section className="auth-visual auth-visual-register"><Link className="brand-lockup" href="/"><span className="brand-orbit">◌</span><span><b>VOID</b><small>Versatile Orchestrated Intelligent Dispatcher</small></span></Link><div><p className="eyebrow">A BETTER WAY TO WORK</p><h1>Start with<br /><em>your intent.</em></h1><p>A calm workspace for turning meaningful requests into controlled, validated outcomes.</p></div><div className="auth-visual-note">✦ <span>Your workspace starts private</span></div></section><section className="auth-panel"><div className="auth-form-wrap"><p className="eyebrow">CREATE ACCOUNT</p><h2>Create your VOID account</h2><p className="muted">Begin with a simple profile. You can tune execution later.</p><form onSubmit={submit}><label>Full name<input required value={form.full_name} onChange={(event) => update("full_name", event.target.value)} /></label><label>Email address<input type="email" required autoComplete="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></label><label>Password<input type="password" required autoComplete="new-password" value={form.password} onChange={(event) => update("password", event.target.value)} /><small className="field-hint">8+ characters, uppercase, lowercase, and number</small></label><label>Confirm password<input type="password" required autoComplete="new-password" value={form.confirm} onChange={(event) => update("confirm", event.target.value)} /></label>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary button-wide" disabled={loading}>{loading ? "Creating account..." : "Create account"}</button></form><p className="auth-switch">Already have an account? <Link href="/login">Sign in</Link></p></div></section></main>;
}
