import Link from "next/link";

const flow = ["Your intent", "Intent Gate", "Mission Kernel", "Agents + models + tools", "Validation", "Result + learning report"];
const features = [
  ["Governed orchestration", "Every mission follows explicit policy, permissions, and validation boundaries."],
  ["Three execution modes", "Choose AUTO, GUIDED, or MANUAL control without losing governance."],
  ["Evidence you can inspect", "Results carry source evidence, artifacts, and safe execution summaries."],
  ["Private by design", "Projects, files, and mission records stay scoped to their owner."],
];

export default function LandingPage() {
  return <main className="landing-page">
    <nav className="landing-nav"><Link className="brand-lockup" href="/"><span className="brand-orbit">◌</span><span><b>VOID</b><small>Versatile Orchestrated Intelligent Dispatcher</small></span></Link><div className="landing-links"><a href="#product">Product</a><a href="#workflow">How it works</a><a href="#security">Security</a><Link href="/login">Sign in</Link><Link className="button button-primary" href="/register">Get started</Link></div></nav>
    <section className="landing-hero"><div className="hero-copy"><p className="eyebrow">GOVERNED AI EXECUTION PLATFORM</p><h1>Your intent.<br /><em>VOID&apos;s orchestration.</em></h1><p className="hero-lede">From a simple request to a controlled, validated result. VOID coordinates work with transparency, security, and measurable outcomes.</p><div className="hero-actions"><Link className="button button-primary" href="/register">Turn intent into execution <span>↗</span></Link><a className="button button-secondary" href="#workflow">Explore how it works</a></div><div className="trust-row"><span>● Local-first</span><span>● Policy-aware</span><span>● Evidence-backed</span></div></div><div className="flow-visual" aria-label="VOID execution flow">{flow.map((item, index) => <div className="flow-node" key={item}><span className="flow-index">0{index + 1}</span><strong>{item}</strong>{index < flow.length - 1 && <i />}</div>)}<div className="floating-status status-one">✓ Policy checked</div><div className="floating-status status-two">✓ Validation passed</div></div></section>
    <section id="product" className="landing-section intro-section"><div><p className="eyebrow">WHAT IS VOID?</p><h2>Calm intelligence.<br />Controlled execution.</h2></div><div><p className="section-lede">You decide what needs to be done. VOID determines the safest and most effective way to execute it, or lets you configure the execution yourself.</p><div className="mode-grid"><article><span>AUTO</span><h3>Let VOID choose</h3><p>Minimal setup for fast, governed execution.</p></article><article><span>GUIDED</span><h3>Review the plan</h3><p>Inspect strategy, risk, cost, privacy, and tools.</p></article><article><span>MANUAL</span><h3>Configure deeply</h3><p>Advanced control while policy still applies.</p></article></div></div></section>
    <section id="workflow" className="landing-section workflow-section"><p className="eyebrow">HOW IT WORKS</p><h2>A clear path from thought to outcome.</h2><div className="steps">{["Express your intent", "Understand the mission", "Select capabilities", "Execute under policy", "Receive validated results"].map((step, index) => <article key={step}><span>0{index + 1}</span><h3>{step}</h3><p>{["Describe the work in your own words.", "VOID turns intent into an executable mission.", "Only permitted agents, models, and tools are selected.", "Tasks run with checkpoints and observable state.", "Results arrive with evidence and an execution report."][index]}</p></article>)}</div></section>
    <section id="security" className="landing-section feature-section"><div><p className="eyebrow">BUILT FOR TRUST</p><h2>Power with boundaries.</h2><p className="section-lede">VOID keeps orchestration behind a governed backend. Your interface stays clear, your data stays scoped, and important decisions remain inspectable.</p></div><div className="feature-grid">{features.map(([title, detail]) => <article key={title}><span className="feature-symbol">✦</span><h3>{title}</h3><p>{detail}</p></article>)}</div></section>
    <section className="landing-cta"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Turn intent into execution.</h2><p>Start with one bounded mission and see exactly what happened.</p><Link className="button button-primary" href="/register">Create your VOID account <span>↗</span></Link></section>
    <footer className="landing-footer"><span className="brand-word">VOID</span><span>Versatile Orchestrated Intelligent Dispatcher</span><span>Local V1 · Governed execution</span></footer>
  </main>;
}
