"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

const API_BASE = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://127.0.0.1:8000";
export default function LoginPage() {
  const router = useRouter(); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { if (localStorage.getItem("void_access_token")) router.replace("/workspace"); }, [router]);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch(`${API_BASE}/api/v1/auth/login`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); const data = await response.json(); if (!response.ok) throw new Error("We couldn't sign you in with those details."); localStorage.setItem("void_access_token", data.access_token); const next = new URLSearchParams(window.location.search).get("next"); router.replace(next?.startsWith("/") ? next : "/workspace"); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "Sign in failed."); } finally { setLoading(false); } }
  return <main className="auth-page"><section className="auth-visual"><Link className="brand-lockup" href="/"><span className="brand-orbit">◌</span><span><b>VOID</b><small>Controlled execution</small></span></Link><div><p className="eyebrow">WELCOME BACK</p><h1>Pick up where<br /><em>your intent left off.</em></h1><p>Review missions, inspect evidence, and continue work with the clarity of a governed system.</p></div><div className="auth-visual-note">◌ <span>Policy boundary online</span></div></section><section className="auth-panel"><div className="auth-form-wrap"><p className="eyebrow">SIGN IN</p><h2>Welcome back to VOID</h2><p className="muted">Enter your account details to continue.</p><form onSubmit={submit}><label>Email address<input type="email" required autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} /></label><label>Password<div className="password-field"><input type={show ? "text" : "password"} required autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} /><button type="button" onClick={() => setShow(!show)}>{show ? "Hide" : "Show"}</button></div></label><div className="form-meta"><label className="check"><input type="checkbox" /> Remember device</label><Link href="/forgot-password">Forgot password?</Link></div>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary button-wide" disabled={loading}>{loading ? "Signing in..." : "Sign in"}</button></form><p className="auth-switch">Don&apos;t have an account? <Link href="/register">Create your VOID account</Link></p></div></section></main>;
}
